<?php

/*
  Sessions
  - Session Is Stored On The Server
  - Session Store Only A User Key In Cookie To Know Its You
  - Key Are Generated By PHP Engine So Its Almost Impossible To Guess
  - You Need To Add It Before Any Output
*/

session_start();
// session_destroy();
if ($_SERVER["REQUEST_METHOD"] === "POST") {
    if ($_POST["name"] == "ashrakt") {
        $_SESSION['name'] = "ashrakt";
        $_SESSION['id'] = 1;
    }
}
if (isset($_SESSION['name'])) {
    echo "welcome" .  $_SESSION['name'];
    echo "<a href='logout.php'>logout</a>" ;
} else {

?>
    <form method="POST" action="">
        <input type="text" name="name">
        <input type="submit">
    </form>
<?php


}



// echo '<pre>';
//   print_r($_SESSION);
//   echo '</pre>';

// echo "<a href='session2.php'>Test</a>" ;